version: '3.7'

services:
  my1562bot:
    image: my1562bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_FILE: /run/secrets/my1562bot_env
      DB_DRIVER: mysql
      DB_CONNECTION: root:toor@tcp(db)/bot?charset=utf8mb4&parseTime=True&loc=Local
    secrets:
      - my1562bot_env
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: bot
    ports:
      - 13306:3306
    volumes:
      - dbdata:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  
volumes:
  dbdata:
secrets:
  my1562bot_env:
    file: ./.env